In [2]:
# your code here
# Import necessary libraries
import pandas as pd                # Handle tabular data
import numpy as np                # Handle missing values, NaN, and mathematical operations
import dateparser                 # Parse date/time from natural language strings
from datetime import datetime     # Work with date and time objects
from collections import Counter   # Count errors or anomalies in data
import math                       # Mathematical functions
import matplotlib.pyplot as plt   # Plotting library
import seaborn as sns             # Visualization with advanced plots
import matplotlib.ticker as ticker

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/DuyLinh-Data/code_via_codex/main/google.csv"

df = pd.read_csv(url)

df.sample(5)

,date,open,high,low,close,adj_close,volume
1497,2010-07-30,12.042395,12.133383,12.196196,11.990490,12.003253,85678236
1483,2010-07-12,11.818361,11.907658,11.997998,11.788789,11.821071,133242624
3222,2017-06-07,49.699478,50.075001,50.195499,49.793499,49.954498,27482000
655,2007-03-28,11.471882,11.558559,11.647648,11.515265,11.558308,183480336
2696,2015-05-06,26.553370,26.754000,27.196501,26.612000,27.132000,39034000

In [4]:
# Convert column headers to lowercase

import pandas as pd
import re

df.columns = [re.sub(r'\W+', '_', col.lower().strip()) for col in df.columns]

In [5]:
df.sample(5)

,date,open,high,low,close,adj_close,volume
2431,2014-04-16,27.983562,28.195000,28.200001,27.655001,27.885000,91644000
11,2004-09-03,2.483984,2.502753,2.546046,2.485485,2.526276,103048848
3500,2018-07-16,59.376865,59.825500,60.435501,59.669998,60.190498,26784000
1593,2010-12-15,14.661494,14.772272,14.926176,14.743493,14.869870,86621292
1536,2010-09-24,13.096490,13.195445,13.208959,12.969469,13.056557,134141724